### ISSUE TITLE
SSL Connection?

### ISSUE THREAD

**Issue by James-Firth** [TablePlus/DataFlow-Issue-Tracker#3]
When trying to connect to a Postgres DB I get `error: SSL connection is required. Please specify SSL options and retry.`

But I don't see the option where to add those parameters (I don't _think_ I want "over SSH").

Where can I do that?

**Comment by huyphams** [comment]
Hi @James-Firth currently we suspend this project for redesigning. You could try out new alternative https://boltsql.com (we will bring the board to Bolt SQL in the future releases).

**Comment by James-Firth** [comment]
hi @huyphams thanks for letting me know! I'll keep my eye on boltsql.
TablePlus has been fantastic for my SQL needs, I was looking at this mostly for the possibility of making internal tools
